Add an example collision handler to examples/src/melon.c
c-krit/ferox pull request #19
Opened 2023-11-25 07:54 UTC by CJongSeong

**Before submitting a pull request, please check:**

- [ ] I have performed a self-review of my own code.
- [ ] My code follows the style guidelines of this project.

---

## What does this pull request do?
같은 색상의 원이 충돌 시 한 단계 높은 원으로 합쳐지는 기능을 추가했습니다.

## Why do we need this pull request?
해당 코드로 작성한 수박 게임은 원래 합쳐지는 기능이 존재하나 현재 코드에는 구현되어 있지 않기 때문입니다.

## How did you test your pull request?
직접 make하여 정상적으로 작동함을 확인하였습니다.

2023-11-25 08:01 UTC, jdeokkim requested changes
코드 리뷰 확인해주세요~

2023-11-25 08:01 UTC, jdeokkim commented on examples/src/melon.c
> +#include <stdio.h>
`<stdio.h>` 헤더 파일은 이 예제 코드에서 사용하지 않기 때문에, 이 줄은 그냥 없애는 것이 좋을 것 같습니다!

2023-11-25 08:01 UTC, jdeokkim commented on examples/src/melon.c
> +static void OnPreStep(frBodyPair key, frCollision *value);
이 줄 맨 앞에 개행 문자 하나만 넣어주세요~

```c
static void InitExample(void);
static void UpdateExample(void);
static void DeinitExample(void);

static void OnPreStep(frBodyPair key, frCollision *value);
```

2023-11-25 08:10 UTC, CJongSeong commented on examples/src/melon.c
> +static void OnPreStep(frBodyPair key, frCollision *value);
stdio.h 제거 및 개행 문자 추가했습니다!

2023-11-25 09:49 UTC, jdeokkim approved these changes

2023-11-25 09:49 UTC, merged

2023-11-27 06:24 UTC, jdeokkim commented
감사합니다 👍